// Code generated by contractcheck from contracts/openapi/{public,internal}.json; DO NOT EDIT.
package echoscan

import (
	"net/url"
	"strings"
)

func getReportPath(imprint string) string {
	return strings.Replace("/api/v1/fingerprint/report/{imprint}", "{imprint}", imprint, 1)
}
func bindAccountAndGetReportPath(imprint string) string {
	return strings.Replace("/api/v1/fingerprint/report/{imprint}", "{imprint}", imprint, 1)
}
func getImprintHistoryPath(imprint string) string {
	return strings.Replace("/api/v1/fingerprint/imprint/{imprint}/history", "{imprint}", imprint, 1)
}
func internalDebugReportPath(imprint, identityScope string) string {
	return strings.Replace("/api/v1/internal/fingerprint/report/{imprint}", "{imprint}", imprint, 1) + "?identityScope=" + url.QueryEscape(identityScope)
}
func internalDebugDetailsPath(imprint, identityScope string) string {
	return strings.Replace("/api/v1/internal/fingerprint/details/{imprint}", "{imprint}", imprint, 1) + "?identityScope=" + url.QueryEscape(identityScope)
}
